kind: pipeline
name: default
clone:
  depth: 1

# XXX hack for cwd failure
workspace:
  base: /tmp
  path: "."
# /XXX

steps:
- name: build-master
  image: plugins/ecr
  settings:
    repo: 577012953595.dkr.ecr.us-west-2.amazonaws.com/relay-web-app
    registry: 577012953595.dkr.ecr.us-west-2.amazonaws.com
    region: us-west-2
    tags: dev,commit-${DRONE_COMMIT},build-${DRONE_BUILD_NUMBER}
    cache_from: 577012953595.dkr.ecr.us-west-2.amazonaws.com/relay-web-app:dev
    when:
      branch:master
- name: build-release
  image: plugins/ecr
  settings:
    repo: 577012953595.dkr.ecr.us-west-2.amazonaws.com/relay-web-app
    registry: 577012953595.dkr.ecr.us-west-2.amazonaws.com
    region: us-west-2
    tags: prod,commit-${DRONE_COMMIT},build-${DRONE_BUILD_NUMBER}
    when:
      branch:release
