kind: pipeline
name: default

# XXX hack for cwd failure
workspace:
  base: /tmp
  path: "."

# /XXX

steps:
- name: publish  
  image: plugins/ecr
  settings:
    repo: 577012953595.dkr.ecr.us-west-2.amazonaws.com/relay-web-app
    registry: 577012953595.dkr.ecr.us-west-2.amazonaws.com
