kind: pipeline
name: default
clone:
  depth: 1
trigger:
  event:
  - push
steps:
- name: build
  image: plugins/ecr
  privileged: true
  settings:
    repo: 577012953595.dkr.ecr.us-west-2.amazonaws.com/relay-web-app
    registry: 577012953595.dkr.ecr.us-west-2.amazonaws.com
    region: us-west-2
    tags: commit-${DRONE_COMMIT},dev-build-${DRONE_BUILD_NUMBER}
    build_args:
    - source_version=${DRONE_COMMIT}
    - build_target=ci
- name: deploy-master
  image: quay.io/honestbee/drone-kubernetes
  when:
    branch:
    - master
  settings:
    kubernetes_server: https://172.20.0.1
    kubernetes_token:
      from_secret: drone-deploy-token
    kubernetes_cert:
      from_secret: drone-deploy-cert
    deployment: relay-web-app
    repo: 577012953595.dkr.ecr.us-west-2.amazonaws.com/relay-web-app
    container: web
    tag: commit-${DRONE_COMMIT}
- name: deploy-bleeds
  image: quay.io/honestbee/drone-kubernetes
  when:
    branch:
    - bleeds
  settings:
    kubernetes_server: https://172.20.0.1
    kubernetes_token:
      from_secret: drone-deploy-token
    kubernetes_cert:
      from_secret: drone-deploy-cert
    deployment: relay-web-app-bleeds
    repo: 577012953595.dkr.ecr.us-west-2.amazonaws.com/relay-web-app
    container: web
    tag: commit-${DRONE_COMMIT}
- name: notify
  image: plugins/webhook
  settings:
    urls: http://172.20.207.235/drone
  when:
    status:
    - success
    - failure
