kind: pipeline
name: default
clone:
  depth: 10

# XXX hack for cwd failure
workspace:
  base: /tmp
  path: "."
# /XXX

steps:
- name: build
  image: docker
  commands:
  - env
  - docker build .
- name: push
  image: plugins/ecr
  settings:
    repo: 577012953595.dkr.ecr.us-west-2.amazonaws.com/relay-web-app
    registry: 577012953595.dkr.ecr.us-west-2.amazonaws.com
    region: us-west-2
    tags: dev
    when:
      branch:master
