kind: pipeline
name: default
clone:
  depth: 1

# XXX hack for cwd failure
workspace:
  base: /tmp
  path: "."
# /XXX


trigger:
  branch:
  - master
  event:
  - push

steps:
- name: build-master
  image: plugins/ecr
  privileged: true
  settings:
    repo: 577012953595.dkr.ecr.us-west-2.amazonaws.com/relay-web-app
    registry: 577012953595.dkr.ecr.us-west-2.amazonaws.com
    region: us-west-2
    tags: dev,commit-${DRONE_COMMIT},build-${DRONE_BUILD_NUMBER}
  volumes:
   - name: docker
     path: /var/run/docker.sock
- name: deploy
  image: quay.io/honestbee/drone-kubernetes
  settings:
    kubernetes_server: https://kubernetes
    deployment: relay-web-app
    repo: 577012953595.dkr.ecr.us-west-2.amazonaws.com/relay-web-app
    container: web
    tag: commit-${DRONE_COMMIT}

volumes:
- name: docker
  host:
    path: /var/run/docker.sock
