kind: Service
apiVersion: v1
metadata:
  name: relay-web-app-public
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 1080
  selector:
    app: relay-web-app
