// vim: ts=4:sw=4:expandtab

(function() {
    'use strict';

    self.F = self.F || {};

    async function getMessage(receipt) {
        const m = new F.Message({sent_at: receipt.get('sent_at')});
        try {
            await m.fetch();
        } catch(e) {
            if (e.message !== 'Not Found') {
                throw e;
            }
            return;
        }
        return m;
    }

    F.deliveryReceiptQueue = new (Backbone.Collection.extend({
        /* TODO:  The only (meaningful) way to correlate these currently is by the
         * sent_at timestamp of the message.
         *
         * I think we may need to augment all clients to include a dataMessage along
         * with the syncMessage that includes various pieces of metadata.  Namely the
         * message id generated by the sender for perfect lookup. */

        initialize: function() {
            this.on('add', this.onAdd);
        },

        drain: function(message) {
            /* Drain receipts for a message model. */
            const receipts = this.where({sent_at: message.get('sent_at')});
            this.remove(receipts);
            return receipts;
        },

        onAdd: async function(receipt) {
            const message = await getMessage(receipt);
            if (!message) {
                return;
            }
            message.addDeliveryReceipt(receipt);
            await message.save();
            this.remove(receipt);
        }
    }))();


    F.readReceiptQueue = new (Backbone.Collection.extend({
        initialize: function() {
            this.on('add', this.onAdd);
        },

        drain: function(message) {
            /* Drain receipts for a message model. */
            const receipts = this.where({sent_at: message.get('sent_at')});
            this.remove(receipts);
            return receipts;
        },

        onAdd: async function(receipt) {
            const message = await getMessage(receipt);
            if (!message) {
                return;
            }
            await message.markRead(receipt.get('read_at'));
            this.remove(receipt);
        }
    }))();
})();
